sever:
  port: 8090

spring:
  application:
    name: monitor
  security:
    user:
      name: admin
      password: admin

eureka:
  client:
    fetchRegistry: true
    #register-with-eureka: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    instanceId: ${spring.application.name} #define el nombre de instancia para que aparezca en eureka server
    hostname: localhost
    prefer-ip-address: true #registra ip no hostname
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    metadata-map:
      instanceId: ${instance.id}
  server:
    enableSelfPreservation: false

environment:
  hostname: ${spring.application.name}
